version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=p7M4rSzg5?
    ports:
      - 1433:1433 

  maarquest.api:
    image: ${DOCKER_REGISTRY-}maarquestapi
    build:
      context: .
      dockerfile: Maarquest.API/Dockerfile
    depends_on:
      - db

  maarquest.web:
    image: ${DOCKER_REGISTRY-}maarquestweb
    build:
      context: .
      dockerfile: Maarquest.WEB/Dockerfile
    ports: 
      - 8080:80
    depends_on:
      - maarquest.api